export enum CsContentType {
    CLASSROOM_TEACHING_VIDEO = 'ClassroomTeachingVideo',
    CONCEPT_MAP = 'ConceptMap',
    COURSE = 'Course',
    CURIOSITY_QUESTION_SET = 'CuriosityQuestionSet',
    E_TEXTBOOK = 'eTextBook',
    EXPERIENTIAL_RESOURCE = 'ExperientialResource',
    EXPLANATION_RESOURCE = 'Explanation Resource',
    EXPLANATION_VIDEO = 'Explanation Video',
    FOCUS_SPOT = 'FocusSpot',
    LEARNING_OUTCOME_DEFINITION = 'LearningOutcomeDefinition',
    MARKING_SCHEME_RUBRIC = 'MarkingSchemeRubric',
    PEDAGOGY_FLOW = 'PedagogyFlow',
    PRACTICE_QUESTION_SET = 'PracticeQuestionSet',
    PRACTICE_RESOURCE = 'PracticeResource',
    READING_MATERIAL = 'ReadingMaterial',
    SELF_ASSESS = 'SelfAssess',
    TEACHING_METHOD = 'TeachingMethod',
    TEXTBOOK = 'Textbook',
    COLLECTION = 'Collection',
    EXPLANATION_READING_MATERIAL = 'ExplanationReadingMaterial',
    LEARNING_ACTIVITY = 'LearningActivity',
    LESSON_PLAN = 'LessonPlan',
    LESSON_PLAN_RESOURCE = 'LessonPlanResource',
    PREVIOUS_BOARD_EXAM_PAPERS = 'PreviousBoardExamPapers',
    RESOURCE = 'Resource'
}
