export enum CsContentType {
    CLASSROOM_TEACHING_VIDEO = 'ClassroomTeachingVideo',
    CONCEPT_MAP = 'ConceptMap',
    COURSE = 'Course',
    CUROSIRTY_QUESTION_SET = 'CuriosityQuestionSet',
    ETEXTBOOK = 'eTextBook',
    EXPEPERIENTIAL_RESOURCE = 'ExperientialResource',
    EXPLANATION_RESOURCE = 'Explanation Resource',
    EXPLANATION_VIDEO = 'Explanation Video',
    FOCUS_SPOT = 'FocusSpot',
    LEARNING_OUTCOME_DEFINITION = 'LearningOutcomeDefinition',
    MARKINGSCHEME_RUBRIC = 'MarkingSchemeRubric',
    PEDAGOGY_FLOW = 'PedagogyFlow',
    PRACTICE_QUESTIONSET = 'PracticeQuestionSet',
    PRACTICE_RESOURCE = 'PracticeResource',
    READING_MATERIAL = 'ReadingMaterial',
    SELF_ASSESS = 'SelfAssess',
    TEACHING_METHOD = 'TeachingMethod',
    TEXTBOOK = 'Textbook',
    COLLECTION = 'Collection',
    EXPLANATION_READING_MATERIAL = 'ExplanationReadingMaterial',
    LEARNING_ACTIVITY = 'LearningActivity',
    LESSONPLAN = 'LessonPlan',
    LESSONPLAN_RESOURCE = 'LessonPlanResource',
    PREVIOIS_BOARD_EXAMPAPERS = 'PreviousBoardExamPapers',
    RESOURCE = 'Resource'
}
